### ISSUE TITLE
Game hangs

### ISSUE THREAD

**Issue by adnanusman** [ignacioxd/gosch-game#7]
When I hit down and spacebar (fire) together, the game hung up.

**Comment by ignacioxd** [comment]
Thanks for the report! This is a known issue that @Pepper is looking into. It has to do with the animation JSON file of the Ice Monster. The Fire Monster and the Spider should be working properly.

**Comment by PepperAddict** [comment]
Hey I have the same issue for any fighting animation pointing down whether it be down-left or down-right. and I can't seem to figure out why. I thought it could be because fighting had 8 frames of animation while the others 6 so I converted fighting to 6 frames and that didn't help.   May need some help figuring this one out.

**Comment by ignacioxd** [comment]
Animations all looking good on my end on all directions. More frames result in smoother animations, but I think they look great as they are. Are we ready to close this issue?

**Comment by adnanusman** [comment]
No, It still hangs for me when I do 'down + spacebar', I have the service workers set to update on reload and cleaned all my caches.

**Comment by ignacioxd** [comment]
Down + spacebar works for me here. Do you get an error on the console?

**Comment by adnanusman** [comment]
This is the error in the console:

Uncaught TypeError: Cannot read property 'frame' of undefined
    at initialize.updateFrame (phaser.min.js:1)
    at initialize.load (phaser.min.js:1)
    at initialize.load (phaser.min.js:1)
    at initialize.load (phaser.min.js:1)
    at initialize.play (phaser.min.js:1)
    at IceMonster.setAnimation (Character.js:47)
    at DungeonScene.update (DemoScene.js:39)
    at initialize.step (phaser.min.js:1)
    at initialize.update (phaser.min.js:1)
    at Game.step (phaser.min.js:1)

**Comment by ignacioxd** [comment]
Could it be that you have a cached version of the JSON animations?

**Comment by adnanusman** [comment]
Yes, you are correct. Opening in incognito window cleared the issue. This thing is resolved.
